# Database Configuration
LOCAL_TABLE=sessions #do not change hardcoded in the service
LOCAL_TABLE_CONFIG=CONFIGURATION_TABLE
CLOUD_TABLE=your_table_name
CLOUD_TABLE_CONFIG=config_table_name
LOCAL_DB=user_sessions.db #do not change hardcoded in the service
JDBC_URL_CLOUD=your_db_url
JDBC_USERNAME_CLOUD=your_db_username
JDBC_PASSWORD_CLOUD=your_db_password

# System Settings
ADMIN_PASSWORD=admin
SYSTEM_NO=LAB-M1 #this denotes the default no assigned