# Local SQLite Tables
LOCAL_TABLE=sessions
LOCAL_TABLE_CONFIG=CONFIGURATION_TABLE
LOCAL_DB=user_sessions.db

# Edge functions
CLOUD_FUNCTION_INSERT=insert-records  #Function names
CLOUD_FUNCTION_SYNC=fetch-all-config

# Database Project info
PROJECT_URL=YOUR_DB_URL
ANON_KEY=YOUR_ANON_KEY


# System Settings
ADMIN_PASSWORD=root
SYSTEM_NO=M-1
LAB_NAME=Lab